env:
  browser: true
  commonjs: true
  es2021: true
  jest: true
extends:
  - airbnb-base
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
overrides:
  - files: "*.js" # Adjust the pattern as needed
    rules:
      "no-plusplus": "off"
